import Foundation

public struct MockTemplate {
    let mockedTypes: [MockedType]
    let imports: [String]
    let testableImports: [String]

    public init(mockedTypes: [MockedType], imports: [String], testableImports: [String]) {
        self.mockedTypes = mockedTypes
        self.imports = imports
        self.testableImports = testableImports
    }

    func renderImports() -> [String] {
        let regularImports = Set(["XCTest", "UltiMock"] + imports).subtracting(testableImports).sorted()
        let testables = Set(testableImports).sorted()

        return regularImports.map { "import \($0)" } +
            testables.map { "@testable import \($0)" }
    }

    @StringBuilder
    public func render() -> String {
        renderImports()
        "\n// Generated by UltiMock. DO NOT EDIT!"

        for type in mockedTypes {
            type.mockSyntax.formatted().description
        }
    }
}
